### PR TITLE
design tweaks

### LINKED ISSUE #382: Correct the Topics font Weight
On the Course homepage in the course info section, the Text in the topics list is boldened when it should resemble the weight of the other text within the course info section. 

Screen Shot 2020-11-19 at 5 02 53 PM

### LINKED ISSUE #384: Topics Section Titles
Can we restyle the topics section titles to resemble the Course Info and Course Features sections? Also, The text size for the section titles should be 16px they are currently 19.2px.

Screen Shot 2020-11-19 at 5 20 58 PM

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

closes #382 
closes #384

#### What's this PR do?

restyles the topic font-weight and the titles / spacing in the course info

#### How should this be manually tested?

look at the course info on both mobile and on desktop and make sure that things look alright!

#### Screenshots (if appropriate)

Screenshot from 2020-11-20 14-43-46
Screenshot from 2020-11-20 14-43-35

### CODE REVIEW

**Comment by Ferdi** [comment]
Can we rename the title from Topic(s) to "Topics" ?

**Comment by aliceriot** [comment]
Screenshot from 2020-11-20 14-49-26

**Comment by Ferdi** [comment]
Did you reduced the font weight on purpose 

Screen Shot 2020-11-20 at 2 54 59 PM

Looks good, i'm just asking

**Comment by aliceriot** [comment]
for this one: https://github.com/mitodl/hugo-course-publisher/issues/382 I just removed the bolding

**Comment by Ferdi** [comment]
ok, i think this is good enough for now imo

**Comment by gumaerc** [comment]
@aliceriot should we be reducing the font weight on the course home page topics as well?
image
@abdulkdawson 's screenshot in [this](https://github.com/mitodl/hugo-course-publisher/issues/382) issue seem to be referencing that and not the expandable ones in the course info drawer.  Should all of them be the same weight?

**Comment by aliceriot** [comment]
ah forgot about the seaprate thing on the home screen. I'm pretty sure they're supposed to all be not-bold, they don't look bold [here](https://projects.invisionapp.com/d/main#/console/18609637/435953153/preview)

**Comment by aliceriot** [comment]
and I ran that screenshot above by Abdul earlier so I think it should be not-bold in both places

**Comment by aliceriot** [comment]
updated to address the homepage one too:

Screenshot from 2020-11-20 16-44-41

**Comment by gumaerc** [comment]
The font size change in desktop course info for the titles is looking good.  I am a bit concerned in general though with the amount of pixel size font declarations, shouldn't we be using `rem` for automatic scaling based on DPI / screen size?  The base font size is `16px`, so it would be just `1rem`.

**Comment by aliceriot** [comment]
I wanted to just make sure that it was going to do what Abdul is intending at all screen sizes, so that's why I went with px for those

**Review by gumaerc — APPROVED** [review]
:+1:

**Pull request merged**
