### PR TITLE
Topics widget

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
https://trello.com/c/kFngfkoX/28-course-by-topic-widget
https://trello.com/c/bD5IxJqX/51-topics-widget-update

Adds a new hierarchial topics structure to sample markdown and the UI to display it in a new partial called "topic.html"

#### How should this be manually tested?
Run the site or check out the deploy preview.  Look at the different courses and make sure the topics look right and that you can expand / collapse the different levels.

#### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Comment by aliceriot** [comment]
wow it's pr :100: ! :tada: :fireworks:

**Comment by aliceriot** [comment]
just two comments on the styling:

Screenshot from 2020-03-12 10-42-30

- the spacing looks a little inconsistent, look at the padding between "Media Studies" and "Digital Media" vs "Digital Media" and "Visual Arts"
- it looks to my eyes like the little open / close chevron isn't quite aligned correctly with the text

**Comment by gumaerc** [comment]
@aliceriot I updated the styling a bit on this and I think it's closer now.  Let me know what you think.

**Comment by gumaerc** [comment]
[Carey Gumaer](https://trello.com/c/fxruV7bF/41-carey-gumaer)

**Pull request merged**
