### PR TITLE
unified content structure

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Related to https://trello.com/c/bVQwTyeU/170-download-course-material-should-be-a-button-in-course-info

#### What's this PR do?
Firstly, this PR adds updated course markdown based on the output of [this](https://github.com/mitodl/ocw-to-hugo/pull/55) PR.  It adds the `type` and `layout` front matter keys to every page so that they are properly identified by Hugo.  The main purpose of this PR however is to remove dependency on finding the course home page through static string building.  This allows us to use the `contentDir` argument to specify a specific course to render as a single site.  I've accomplished this by creating 2 themes for the site: `multi_course` (the default) and `single_course`.  The way we've structured our content, the course info metadata lives in the markdown of the course home page, which is why we need to obtain the course home page to render content that uses this information.  Thus, inside the two theme folders you will see a `partials` folder each containing a `chp_partial.html` file.  The purpose of these partials is essentially to call another partial with the context of the course home page, which needs to be acquired differently depending on how the site is being rendered.  It's used like this:

`{{ partial "chp_partial.html" (dict "partial" "course_info.html" "context" .) }}`

By default, the site is rendered in multi-course mode.  The content in the repo is designed to be run this way.  With these changes though, you can now render a site with the root being a single course by using the Hugo `contentDir` argument.  Details about this are below.

#### How should this be manually tested?
First of all, make sure the site will still render with the normal method either using docker or node natively.  By default, it should look as if nothing has changed.  However, you can now either run the dev server or a build against a single course.  For example:

dev server:
`npm run start:single_course -- ../site/content/courses/18-06-linear-algebra-spring-2010`

build and output to `dist`:
`npm run build:hugo:single_course -- ../site/content/courses/18-06-linear-algebra-spring-2010`

Note that the path is prefixed with `..` because this is being run from the context of the node source, which is under `src`.  Either way, the result of the first command is that you should be able to run it and then visit http://localhost:3000/ and be greeted with the course home page for linear algebra.  Running the second command will simply run the Hugo build against the given course.  Verify that you can navigate the single course page just as you would if you selected it through the course index.

### CODE REVIEW

**Comment by mbertrand** [comment]
@gumaerc  not sure if I'm missing a step, but after running `npm run start:single -- ../site/content/courses/18-06-linear-algebra-spring-2010` this is what I get in the browser:

Screen Shot 2020-07-29 at 12 28 22 PM

and there's some errors after running the command:
```
Building sites … npm ERR! missing script: start:webpack
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     build:webpack
npm ERR!     start:multi:webpack

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mbertrand/.npm/_logs/2020-07-29T16_26_36_860Z-debug.log

                   | EN
-------------------+------
  Pages            | 106
  Paginator pages  |   0
  Non-page files   |   0
  Static files     | 411
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Built in 331 ms
Watching for changes in /Users/mbertrand/code/hcplocal/site/{content,data,layouts,static,themes}
Watching for config changes in site/config.toml
Environment: "development"
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at //localhost:3000/ (bind address 0.0.0.0)
Press Ctrl+C to stop
```

if I run `npm start` instead then all the courses render normally.

**Comment by gumaerc** [comment]
@mbertrand I made a mistake in that build script that I corrected.  Also, if you haven't run this project before you'll need to run a `yarn install` first FYI.

**Comment by gumaerc** [comment]
@mbertrand I pushed up a fix for the links.  It was an issue with the `getpage.html` shortcode, which handles getting a Hugo `Page` object within a template using a shortcode, which is basically like a jinja template tag that can be inserted directly into Hugo markdown.  `ocw-to-hugo` generates links to other course sections using this format.  For example:

`{{% getpage "courses/12-001-introduction-to-geology-fall-2013/sections/labs-and-exercises/MIT12_001F13_Ex1_Erth_Mntl" %}}`

Since the `contentDir` argument here is being used to change the root of the site to a specific course, I had to make 2 versions of this shortcode; one for the `multi_course` theme and another for the `single_course` theme.  I also noticed that `pdfjs` was not being built with the single course site, so I fixed that as well.

**Comment by gumaerc** [comment]
@mbertrand Good catch, I accidentally committed a debug line.

**Pull request merged**
