### PR TITLE
home page second pass

### LINKED ISSUE #313: Site header
Consistent site header, based on the one in the new home page design

#### Designs and Mockups

https://invis.io/8PZBP1MUQ79#/436781959_OCW_NexGen_Homepage_11-04-2020_V3

#### Acceptance Criteria:

- [x] MIT OCW logo links to home page
- [x] "Give Now" button links to https://giving.mit.edu/give/to/ocw/?utm_source=ocw&utm_medium=homepage_banner&utm_campaign=nextgen_home
- [x] About / Help / Contact links all show "coming soon" pop-up
- [x] Apply to home page, search results page and all course pages

### LINKED ISSUE #314: Home: update styling and implement top features
Implement the more stable parts of the new home page

#### Designs and Mockups

https://invis.io/DFZBR47WPA7#/436781958_OCW_NexGen_Homepage_11-04-2020_V2

#### Acceptance Criteria:

- [x] Search box (but not the 3 red buttons below)
- [x] Tag line box
  - [x] "Unlocking Knowledge..." 
  - [x] "Learn More" displays "coming soon" pop-up
- [x] New courses (should already be done)
- [x] restyle social buttons
- [x] add corporate logos 
- [x] implement mobile view (https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/437726301/preview?scrollOffset=1705.5)

#### Out of Scope

- Discover Topics
- OCW News
- Learner Stories

### LINKED ISSUE #354: Course Card Issues
Course Card height is off. Current Implementation has the card height at 400px. 

Proper Height: 381px

Course Card Image is too short. Current Implementation has the image at 141px.

Proper Height: 186px

Screen Shot 2020-11-18 at 10 55 34 AM

### LINKED ISSUE #355: Next and Previous Buttons need resizing
Next and Previous buttons are too large.
Proper Specs-
	Text: 16px
	Height: 38px
	Padding: 8px of padding to the left and right of the text including the arrow.

Screen Shot 2020-11-18 at 10 58 00 AM

### LINKED ISSUE #357: Resize Give button
The Give button on the OCW Homepage is too large. The required specs are outlined below:

Button: 158x50px
Text: 28px
Heart Icon: 30x26px

Screen Shot 2020-11-18 at 11 48 06 AM

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

closes #357 
closes #355 
closes #354 
part of #314 
closes #313

#### What's this PR do?

this is

- a second pass on the home screen design
- adding the new top banner to all pages
- fixing several issues pointed out about the current implemention of the home screen, like button heights and so on

#### How should this be manually tested?

check out the branch and look at the relevant designs. The home page should have a responsive design that is close to the mocks.

check out the course pages too - the new site header should be seamlessly integrated there as well, and on the course page as well.

#### Screenshots (if appropriate)

home page:

localhost_3000_(iPhone 6_7_8) (2)

localhost_3000_ (1)

course pages:

localhost_3000_courses_18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018_

search:
localhost_3000_search_

### CODE REVIEW

**Comment by gumaerc** [comment]
In the mocks, the previous / next buttons on Featured Courses seem to be opaque with a white background but here they are transparent:
image
vs
image

**Comment by gumaerc** [comment]
On mobile, it looks like the Give button's text is not lined up with the heart icon:

image
vs
image

**Comment by gumaerc** [comment]
The rounded upper left / right corners of course cards don't appear to have their borders rendered:
image
vs
image

**Comment by gumaerc** [comment]
Similarly to the Give Now button, the Learn More link at the top of the page seems to be using the wrong orange color.  It should be `#FF8A1F` and it's `#FF9A00`.

image
vs
image

**Comment by gumaerc** [comment]
The search box doesn't quite look tall enough and the left padding doesn't look quite right compared to the mock:

image
vs
image

In an inspector I was able to achieve this by changing `pl-5` to `pl-7` on the `input` element, adding `pl-4 pt-1` to the `i` element, and changing the static height on the `input` element in `form.seach-box input` from `50px` to `60px`:
image

**Comment by gumaerc** [comment]
Also with the search box, I think the magnifying glass is supposed to be a different color; `#8A8B8C` instead of `#B0B0B0`.

**Comment by gumaerc** [comment]
The Give Now button should link to https://giving.mit.edu/give/to/ocw/?utm_source=ocw&utm_medium=homepage_banner&utm_campaign=nextgen_home, same as the one in the header, no?

**Comment by gumaerc** [comment]
Should this PR close https://github.com/mitodl/hugo-course-publisher/issues/314 without adding the corporate sponsor logos?

**Comment by gumaerc** [comment]
@aliceriot I went through everything pretty thoroughly and everything I noticed is above.

**Comment by aliceriot** [comment]
I haven't gotten assets for the sponsors yet and didn't want to hold this up any longer

**Comment by gumaerc** [comment]
> I haven't gotten assets for the sponsors yet and didn't want to hold this up any longer

All good, was just thinking we maybe shouldn't auto-close that issue by merging this because it has that checkbox.

**Comment by aliceriot** [comment]
ok that should all be addressed

**Comment by gumaerc** [comment]
Everything looks fixed, except now the Give button has an underline:

image

**Comment by aliceriot** [comment]
ah! dang `href`s

**Review by gumaerc — APPROVED** [review]
:+1: LGTM

**Pull request merged**
