### PR TITLE
Update course result content

### LINKED ISSUE #227: Search: Link course cards to course CHPs
As a user, I'd like to link from the search results to the courses that I find. 

#### Acceptance Criteria:

- [ ] Make sure that the necessary data for creating a link is in the Open search index
- [ ] if possible, log an error to sentry if the user clicks on a course link that doesn't exist

### LINKED ISSUE #230: Search: update course cards
#### Designs and Mockups

See https://projects.invisionapp.com/share/TYYM755E9FJ#/screens/430328458_OCW_Course_Search_Learning_Landing_Page_Courses09-01-2020_No_Facets

#### Acceptance Criteria:

- [ ] remove "Course" 
- [ ] add course number
- [ ] add Level 
- [ ] s/Subject/Topic/
- [ ] add instructors
- [ ] update styling 
- [ ] anything else you see in the design

### PR DESCRIPTION
**Pull request by mbertrand**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [ ] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #227 
Closes #230

#### What's this PR do?
Adds additional info to each course search result (course number, level, instructors) and tweaks the styling to match [the design](https://projects.invisionapp.com/share/TYYM755E9FJ#/screens/430328458_OCW_Course_Search_Learning_Landing_Page_Courses09-01-2020_No_Facets).

#### How should this be manually tested?
Go to the search page and try out some different searches for courses and resources.  The page should look about the same as the design in terms of what's mentioned in the issues, and the course title/thumbnail should load the course URL when clicked in the same tab.

#### Any background context you want to provide?
(Optional)

#### Screenshots
Screen Shot 2020-09-30 at 3 34 15 PM

### CODE REVIEW

**Comment by mbertrand** [comment]
@abdulkdawson @pdpinch screenshots are attached to the PR

**Comment by aliceriot** [comment]
some design notes:

on the design after "Instructor(s)" there is a colon:

Screenshot from 2020-10-01 09-57-41

but on this branch it's a dash:

Screenshot from 2020-10-01 09-57-51

some of the text styling looks a little visually different. for instance the `.resource-type` div looks to have a bigger font and lighter font-weight on the design:

Screenshot from 2020-10-01 10-01-25

than it does on the branch:

Screenshot from 2020-10-01 10-01-30

I think in the design it's listed as `14px` but I'm seeing `13px` on the branch with a 500 font-weight - here's what it looks like with `font-size: 14px` and `font-weight: 400`:

Screenshot from 2020-10-01 10-02-40

wondering if that captures what you were going for @abdulkdawson or whether it needs some more tweaks

**Comment by mbertrand** [comment]
The styling has been updated and dashes changed to colons.

**Review by aliceriot — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
