### PR TITLE
make sidebar look more gitbook-ey

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

none

#### What's this PR do?

this gets the sidebar styling more gitbook-ey-looking

#### How should this be manually tested?

just try it out and make sure it looks alright to you

#### Screenshots (if appropriate)

Screenshot from 2020-03-16 12-17-13

Screenshot from 2020-03-16 12-14-56

for comparison, this is the sidebar on gitbooks:

Screenshot from 2020-03-16 12-15-01

### CODE REVIEW

**Comment by aliceriot** [comment]
sure:

Screenshot from 2020-03-16 14-02-03

**Comment by aliceriot** [comment]
updated the text styling a little bit:

Screenshot from 2020-03-16 16-37-47

**Comment by aliceriot** [comment]
@gumaerc fyi I think this is still awaiting feedback from @Ferdi and @abdulkdawson and I have a list of a few more tweaks to make - I probably should have marked it "draft" for now

**Comment by aliceriot** [comment]
["gitbook" stylesheet](https://trello.com/c/HHJ6g64p/76-gitbook-stylesheet)

**Comment by aliceriot** [comment]
ok I updated things to be in line with @abdulkdawson 's comments and I fixed that weird text-wrapping issue that @gumaerc pointed out:

Screenshot from 2020-03-17 14-08-10

**Comment by gumaerc** [comment]
Text wrapping issue confirmed fixed.

**Comment by abdulkdawson** [comment]
This looks good @aliceriot I was able to review the updates and based on the issues I documented this looks good.

**Comment by aliceriot** [comment]
@odlbot what are you thinking for icons? it might be good to do the header in a separate PR just to ge this one merged

**Comment by aliceriot** [comment]
any more feedback on this PR? Should we do the icons here or merge this and then circle back?

**Pull request merged**
