### PR TITLE
restyle desktop header to be closer to mocks

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?

for this one: https://trello.com/c/aOlRClVV/2-redesign-ocw-course

#### What's this PR do?

basically I've just worked with the course page header a little bit to get it closer to the mocks.
 @abdulkdawson also asked me to remove the 'share' button so I took that out.

I also set up `prettier` to format our `.scss` files b/c why not :)

#### How should this be manually tested?

I think just make sure it looks alright and there's not too much weirdness

#### Screenshots (if appropriate)

Screenshot from 2020-01-29 11-46-42

### CODE REVIEW

**Comment by gumaerc** [comment]
This might mostly have to do with the fact that the design has changed and there is less padding on the left nav, but it seems like maybe there is too much left padding on `#desktop-header .contents`?

ocw-next-header-comparison

@abdulkdawson what do you think?

**Comment by gumaerc** [comment]
Correct me if I'm wrong, but it looks as if the desktop header is not being hidden at mobile widths.  I was using the `large-and-above-only` class, which uses uses bootstrap's media breakpoint include:

```
.large-and-above-only {
  @include media-breakpoint-down(md) {
    display: none;
  }
}
```

ocw-next-mobile-header-comparison

**Comment by aliceriot** [comment]
oops, yeah I removed that and was going to circle back for mobile stuff in a different PR so didn't notice. I'll fix it now

**Comment by aliceriot** [comment]
@gumaerc for the padding I just took the spacing directly from the invision mocks, it would be better probably to use bootstrap classes provided there is a spacing that works for the design (@abdulkdawson )

**Comment by gumaerc** [comment]
> @gumaerc for the padding I just took the spacing directly from the invision mocks, it would be better probably to use bootstrap classes provided there is a spacing that works for the design (@abdulkdawson )

The base variables for bootstrap can be found here:

https://getbootstrap.com/docs/3.4/customize/

You can set any of these by name in `variables.scss` and when bootstrap is imported, it will take those values as overrides during the build process.  You can set the base value for a lot of different classes used to set padding, margin, borders, font size and more.  It's not a one size fits all solution, but I think we should use it where possible.

**Comment by aliceriot** [comment]
ok cool, tbh it's been years since I've used bootstrap. I'll take a look at doing the layout for the header using that stuff and see what I can come up with.

**Comment by gumaerc** [comment]
> ok cool, tbh it's been years since I've used bootstrap. I'll take a look at doing the layout for the header using that stuff and see what I can come up with.

My front end dev experience is also mostly self taught and I'm new here, so if there are standard practices you guys have that I'm missing here please let me know.

**Comment by aliceriot** [comment]
no worries :)

I typically avoid frameworks for major layout stuff and tend to just write the CSS from scratch / almost scratch for things because I prefer to know where all the elements of the layout are coming from. I guess as far as we have a "standard practice" that might be it, but I'm game to try fiddling with bootstrap so we can try to write less CSS on this project, and if we run into a situation where it's not working for us anymore then we can re-evaluate.

I have to admit I don't really like the alphabet soup classes (like `pl-5 md-2` and so on) but I can definitely get over that :)

**Comment by aliceriot** [comment]
ok, I redid the layout for the header spacing to use bootstrap `p` and `m` classes

Screenshot from 2020-01-30 12-26-18

**Comment by gumaerc** [comment]
:+1: LGTM

approved

**Pull request merged**
