### PR TITLE
a few tweaks to cut down bundle size

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

none

#### What's this PR do?

this removes `bootstrap-material-design`, a package which, afaict, isn't doing anything (the site looks identical if I remove it).

I also moved our lodash imports to be pulling from the separate, per-module npm packages, rather than the big single package. We have dependencies that are still pulling the big one in though so...

before:

before

after:

afterwards

#### How should this be manually tested?

Everything in the site should work as normal.

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
I found one slight difference in styling so far between this branch and master/ocw-beta:

Here's what it looks like on master and on ocw-beta.odl.mit.edu (Look at subheadings near the bottom: "TOPICS    SUMMARIES    DESIGN CHALLENGES"):

Screen Shot 2020-11-02 at 4 22 48 PM

And on this branch:

Screen Shot 2020-11-02 at 4 23 01 PM

**Comment by aliceriot** [comment]
Good catch - I'll fix that to be inline with the designs

**Comment by aliceriot** [comment]
I updated the tables to be in light with the mocks (which was actually not the case here _or_ on master!):

Screenshot from 2020-11-03 09-13-33

see this mock for reference: https://projects.invisionapp.com/d/main#/console/18609637/432832563/inspect

**Comment by mbertrand** [comment]
@aliceriot I think those changes still need to be pushed?  Last commit I see is 20 hours ago.

**Comment by aliceriot** [comment]
right you are! it's pushed now

**Review by mbertrand — APPROVED** [review]
Looks great 👍

**Pull request merged**
