### PR TITLE
Left nav hierarchy UI

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
UI part of https://trello.com/c/JkknCyTL/11-hierarchical-left-nav

#### What's this PR do?
Adds a recursive menu_item.html partial that recursively renders all menu items passed in as a collapsible nav using bootstrap collapse classes

#### How should this be manually tested?
Run the site, browse courses that have child nodes (the analytics edge is a good example) and verify that child menu items are rendered and it looks like the design

#### Any background context you want to provide?
The child menu items having all the same name in some cases is a known issue: https://github.com/mitodl/ocw-to-hugo/issues/23

#### Screenshots (if appropriate)

image

image

### CODE REVIEW

**Comment by aliceriot** [comment]
it looks like some courses are deleted here - are they currently incompatible with the UI or something?

**Comment by aliceriot** [comment]
the 'single-variable-calculus' course and others

**Comment by aliceriot** [comment]
one thing i'm thinking about it that on a wider screen the left-side desktop width menu can get a little wide:

Screenshot from 2020-02-20 10-11-28

(that is on a 1080p screen with the window at full width)

maybe we want to have some responsive styling for what bootstrap calls the `xl` breakpoint? for instance we could keep the `width: 100%` on the `nav` item untilt he `xl` breakpoint and then go to `75%`, that gives us this on my 1080p screen:

Screenshot from 2020-02-20 10-26-14


idk just throwing some ideas out :D

**Comment by gumaerc** [comment]
> it looks like some courses are deleted here - are they currently incompatible with the UI or something?

The single variable calculus course got removed because I was working on a different computer yesterday and was using an outdated set of source JSON.  I just re-added it, and on my local setup I'm seeing all 23 test courses in the index page.

**Comment by gumaerc** [comment]
Feedback from @Ferdi and @abdulkdawson from Slack:

- The + signs are a bit too in your face , imo
- In mobile view, the sliding window could be a bit wider
- In mobile view, I wander if + signs should be aligned center with the text.

**Comment by gumaerc** [comment]
@aliceriot Generally I agree with you that in your screenshots it looks like the nav is a bit wide, but I'd also note that the particular example course you're looking at there is pretty barebones.  Some courses have more wordy nav items and / or more of them and use all the space.  Either way if we do reduce the size of the nav at the xl breakpoint, I think the best way to do it would be to use a media breakpoint and institute a max width... something like this:

```
.desktop-nav {
  @include media-breakpoint-up(xl) {
    max-width: 400px;
  }
}
```

**Comment by aliceriot** [comment]
looking good I think, just noticed a few things with the mobile drawer:

Screenshot from 2020-02-20 13-39-49

the "Browse Course Materials" header is shown aligned with all the other items on the design here: https://projects.invisionapp.com/d/main#/console/18552410/404246421/preview

it also looks like on this design we have smaller text for the "children" in the menus: https://projects.invisionapp.com/d/main#/console/18552410/404246422/preview

**Comment by gumaerc** [comment]
@aliceriot I fixed the "browse course material" header in the drawer and made the child item font size smaller.

**Pull request merged**
