### PR TITLE
Style updates to course home page

### LINKED ISSUE #312: CHP: style to match new design
Course Home page new design 

#### Designs and Mockups

https://invis.io/ZAZ6VJ2HRSP#/435537972_OCW_Course_Home_Page_Color_10-22-2020_v2
https://invis.io/QFZ8KA9SH2P#/435953154_OCW_Course_Home_Page_Color_10-27-2020_Course_Info_Collapsed_V2

#### Acceptance Criteria:

- [x]  Same course banner as interior course pages
  - [x] flat color for now, no outline
  - [x] course avatar/icon will be optional; omit for now
- [x] no course drawer on CHP
- [x] large, variably height course image
- [ ] 3 lines of course description display on load, click to read more
- [x] 3 lines of course info display on load, click to read more 
- [x] course feature icons
- [x] screenshot of mobile version 
- [x] screenshot of course with short image, and screenshot of a course with a tall image 

#### Out of Scope

- "Other Versions" (below course features)

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Part of #312 

#### What's this PR do?
It fulfills some of the requirements in #312 
- remove course info drawer on the course home page while keeping it on section pages, on both desktop and mobile
- minor tweaks to course info layout
- topics now inline within course info
- variable height course image for desktop, no image for mobile

Left to do:
 - read more links for course info and course description
 - Fix material-icons #353
 - Banner #351 
 - Coloring/style of mobile view needs work. Mockup: https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/403040977/preview?scrollOffset=2728.5

#### How should this be manually tested?
Click around the course home page, especially the 

#### Context
The Exams course feature icon needs #353 to show up properly

#### Screenshots (if appropriate)
Desktop:
Screenshot_2020-11-18 Course Home Electronic, Optical and Magnetic Properties of Materials Materials Science and Engineerin

Narrower desktop:
Screenshot_2020-11-18 Course Home Electronic, Optical and Magnetic Properties of Materials Materials Science and Engineerin (1)

Wide mobile:
Screenshot_2020-11-18 Course Home Introductory Biology Biology MIT OpenCourseWare

Narrow mobile:
Screenshot_2020-11-18 Course Home Introductory Biology Biology MIT OpenCourseWare(2)

### CODE REVIEW

**Comment by gumaerc** [comment]
The course image looks to be slightly cut off on the left and right, see below:

live:
image
vs this branch:
image

**Comment by gumaerc** [comment]
On the course `15-071-the-analytics-edge-spring-2017`, I don't see topics rendered on the course home page, but I do see the topics tree being rendered in the `topics.html` parser on the interior pages:

image
vs

**Comment by gumaerc** [comment]
In the designs, the course features section seems to have a grey background and some padding / margin to distance it from the content above it:

image
vs
image

**Comment by noisecapella** [comment]
@gumaerc I think the three issues you highlighted should be fixed now

Some new screenshots:
Mobile:
Screenshot_2020-11-18 Course Home The Analytics Edge Sloan School of Management MIT OpenCourseWare(6)

Wide mobile:
Screenshot_2020-11-18 Course Home The Analytics Edge Sloan School of Management MIT OpenCourseWare(5)


Narrow desktop:
Screenshot_2020-11-18 Course Home The Analytics Edge Sloan School of Management MIT OpenCourseWare(4)

Wide desktop:
Screenshot_2020-11-18 Course Home The Analytics Edge Sloan School of Management MIT OpenCourseWare(3)

**Comment by noisecapella** [comment]
@gumaerc looks like I still have some tweaks to make for the course info drawer

**Comment by noisecapella** [comment]
Ok, that should fix the course info panel rendering:

Screenshot_2020-11-18 Syllabus The Analytics Edge Sloan School of Management MIT OpenCourseWare

Screenshot_2020-11-18 Syllabus The Analytics Edge Sloan School of Management MIT OpenCourseWare(1)

**Comment by gumaerc** [comment]
So, the reason this broke is due to the removal of `chp_partial.html`.  When rendering a partial, you have to consider every context in which it might be rendered.  One of the places the course info drawer is called is in `course/baseof.html` which is the base template for all pages with `type: course`.  Since both the course section pages and course home page are of `type: course`, section pages are passing in *their* `.Params` to the `course_info.html` partial during the build.  Since all the course metadata is currently stored on the course home page, the context of the course home page needs to be obtained in this case which is the purpose of `chp_partial.html`.  That being, to call partials with the context of the course home page which has the information you need.

I see that you're trying to add `inPanel` to the arguments passed to the partials that use `course_info`.  Removing `chp_partial.html` will break support for rendering single course pages for the zip builds, which isn't such a big deal at the moment because we have hidden the download functionality for now.  The bigger issue is obtaining the context of the course home page in pages that *aren't* the course home page.  All of this is the primary reason I raised https://github.com/mitodl/hugo-course-publisher/issues/326.  If we move to storing the metadata in Hugo Data Templates, this wouldn't be an issue because the metadata would be available globally.  For now, a quick and dirty solution would be to use the following code in `partial_collapse_list.html`:

```
{{ $id := .id }}
{{ $className := .klass | default "coming-soon" }}
{{ $useLinks := .useLinks | default true }}
{{ with .list }}
{{ if gt (len .) 4 }}
<div class="position-relative pr-3">
  <a class="partial-collapse-toggle-link" href="#partial-collapse-container_{{ $id }}" data-toggle="collapse"
    aria-controls="partial-collapse-container_{{ $id }}" aria-expanded="false">
    <div class="partial-collapse-icon-container">
      <span class="partial-collapse-icon">
        <i class="material-icons md-18"></i>
      </span>
    </div>
  </a>
  <div class="partial-collapse collapse" id="partial-collapse-container_{{ $id }}">
    <ul class="list-unstyled m-0">
      {{ range $item := . }}
      <li>
        {{ if $useLinks }}
        <a href="#" class="partial-collapse-link {{ $className }}">
          {{ $item }}
        </a>
        {{ else }}
        {{ $item }}
        {{end }}
      </li>
      {{ end }}
    </ul>
  </div>
  <div class="partial-collapse-overlay"></div>
</div>
{{ else }}
<ul class="list-unstyled m-0">
  {{ range $item := . }}
  <li>
    {{ if $useLinks }}
    <a href="#" class="{{ $className }}">
      {{ $item }}
    </a>
    {{ else }}
    {{ $item }}
    {{end }}
  </li>
  {{ end }}
</ul>
{{ end }}
{{ end }}
```
This tells Hugo to skip rendering anything inside `{{ with .list }}` if it doesn't exist.  Single course rendering will still be broken, but as long as we're committed to moving to Data Templates it will be fixed when we do that.

A cleaner solution would be to keep `chp_partial.html` intact in both themes and just add an optional `args` array to store extra arguments in like `inPanel`.  For example:

`multi_course/layouts/partials/chp_partial.html`
```
{{ $partial := .partial }}
{{ $context := .context }}
{{ $courseId := .context.Params.course_id }}
{{ $args := .args | default nil }}
{{ range first 1 (where $context.FirstSection.Sections ".Params.course_id" $courseId) }}
  {{ partial $partial (dict "Params" .Params "args" $args) }}
{{ end }} 
```

`single_course/layouts/partials/chp_partial.html`
```
{{ $args := .args | default nil }}
{{ partial .partial (dict "Params" .context.Params "args" $args) }}
```

Then, anywhere you need to call a partial with the context of the course home page, you do it like this:

```
{{ partial "chp_partial.html" (dict "partial" "course_info.html" "context" . "args" (dict "inPanel" true )) }}
{{ partial "chp_partial.html" (dict "partial" "topics.html" "context" .) }}
{{ partial "chp_partial.html" (dict "partial" "course_features.html" "context" . "args" (dict "inPanel" true)) }}
```

I created a branch off of yours with this tested and working here: https://github.com/mitodl/hugo-course-publisher/tree/cg/chp-partial-args-suggestion

Aside from that complicated mess, visually the changes look great.  It's easy to see though why I want to move away from storing the course metadata on the course home page's Front Matter after dealing with this situation.

**Comment by noisecapella** [comment]
Sure, I'll add it back. I had added `course_info` to the section pages so I figured `chp_partial.html` was redundant now, but it looks like at least some video pages don't have that information.

**Review by gumaerc — APPROVED** [review]
:+1: Looks good locally, okay to merge assuming the deploy preview builds successfully.

**Pull request merged**
