### PR TITLE
set up hugo site for multi-course

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] no style changes
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

none

#### What's this PR do?

this copies over an updated-ish copy of the linear algebra course and the geology course and sets up the site for rendering multiple courses. basically:

- courses are moved into `site/content/courses/$COURSE_ID`
- in there there is a `_index.md` file and `resources` directory
- the templates are moved around to render these things properly

I also added a new template for `index.html` which is just a placeholder for now, and a layout at `site/layouts/courseindex/section.html` which ends up being rendered for `/courses`. this is basically just a simple list of the courses registered in the site right now.

The idea is that as we continue improving the pipeline for churning out markdown we can start copy the markdown for all the test courses over into this project, and so any thing we're testing as far as layout changes we can start testing on all the courses at once. This will also make it easy for us to push up new rendered versions of these for people to review (e.g. to github pages or what have you).

In the long run this may or may not be how we want to render these things.

note that to get this working I had to do a little editing of the markdown, to change the menu keys to be course-specific. this will be changed upstream in the ocw-to-hugo repo, and once that is set up I'll make the change over here as well. 

#### How should this be manually tested?

you should be able to pull down the branch and fire it up with no error. visiting `/courses` should give you a list of the included courses (just two right now) and, from there, you should be able to visiting them and click around. there should be no regressions or weirdness there.

### CODE REVIEW

**Comment by gumaerc** [comment]
The course info section isn't being rendered with any data at the moment.  Currently these partials are initialized with `.Site.Home` and then in the partial, the values are being accessed with `.Params.course_info`.  The best way to fix this with multiple courses in mind would be to instead pass in .Params.course_info directory to the course_info partial, then simply access the different properties of the `course_info` object at `.`

**Comment by gumaerc** [comment]
> in there there is a _index.md file and resources directory

Do you mean the sections directory, or is this something else?

**Comment by aliceriot** [comment]
that's referring iirc to `site/content/$COURSE_ID/`. in each course there is an `_index.md` file and a `resources` dir which has all of the sub pages.

**Comment by aliceriot** [comment]
ah forgot about the course info! will fix that.

**Comment by gumaerc** [comment]
> that's referring iirc to `site/content/$COURSE_ID/`. in each course there is an `_index.md` file and a `resources` dir which has all of the sub pages.

I've been calling this `sections`, and that's how the structure is coming out of ocw-to-hugo.  Looking again, it seems as if `12-001-introduction-to-geology-fall-2013` has the course sections both under the `sections` folder and in the root of the course content folder.  It doesn't seem as if the code is referring to anything as being in `resources`, but we should choose one, one way or the other.

**Comment by aliceriot** [comment]
oh sorry I might have mis-typed, I think I meant 'sections'. 'Sections may not be the best terminology to use since it is a term for a content-type folder in Hugo, but it doesn't seem to cause problems so :woman_shrugging:

**Comment by aliceriot** [comment]
I think I might have had a few artifacts of manual JSON editing in `content/courses`, so I just blew it away and re-copied from the stuff you put in dropbox

**Comment by aliceriot** [comment]
ok I think the course info issue should be addressed now

**Comment by gumaerc** [comment]
:+1: LGTM

**Pull request merged**
