### PR TITLE
Course Info Collapsibles

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
https://trello.com/c/kVtunwvL/33-course-info-multiple-departments-multiple-course-numbers

#### What's this PR do?
Implements a new partial for partially collapsible lists and uses it on the relevant items in Course Info.

#### How should this be manually tested?
Run the site, check out Course Info on various courses and make sure it looks / functions right.

#### Screenshots (if appropriate)
image

image

### CODE REVIEW

**Comment by gumaerc** [comment]
[Course Info (Multiple Departments & Multiple Course Numbers)](https://trello.com/c/kVtunwvL/33-course-info-multiple-departments-multiple-course-numbers)

**Comment by aliceriot** [comment]
works great! reading code now

**Comment by gumaerc** [comment]
> works great! reading code now

Just spoke with Abdul about something I was wondering.  If you try and click one of the links, it should be expanding the drawer.  Currently it does nothing.  I'll be working on pushing up a change to fix this shortly.

**Comment by aliceriot** [comment]
actually just noticed one issue, on the "Unified engineering" course (http://localhost:3000/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/) there are both multiple course numbers _and_ multiple professors. there is an issue where expanding one of the two expands both of them - in the following screenshot I only clicked on the open / close toggle for the course numbers, but the professors panel opened too:

Screenshot from 2020-03-02 10-27-26

**Pull request merged**
