### PR TITLE
switch to github actions

### LINKED ISSUE #302: switch from travis -> github actions
à la [open-discussions](https://github.com/mitodl/open-discussions/pull/3204)

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?

closes #302

#### What's this PR do?

This switches from travis to github actions.

#### How should this be manually tested?

The build should pass, and everything should look legit.

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
LGTM.  Just one possibly dumb question, should there be separate test runs for pr and push like there used to be for travis?  Only seeing CI on this PR.

Screen Shot 2020-11-05 at 3 48 10 PM

vs

Screen Shot 2020-11-05 at 3 51 25 PM

**Comment by aliceriot** [comment]
I don't think those are necessary? but I forgot to mark this "in progress" because I actually need to figure out the netlify deployment before this can be merged anyhow

**Comment by aliceriot** [comment]
@mbertrand it seems like Netlify is actually working fine with this setup, so I think we should go forward with this. I don't think we need to duplicate those other travis checks.

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
